name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ homologation ]

jobs:
  php-unit:
    runs-on: ubuntu-latest

    services:
      mysql:
          image: mysql:5.7
          env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: testing_tenancy
          ports:
            - 3306/tcp
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '7.4'
        extensions: mbstring, dom, fileinfo, mysql

    - name: Start mysql service
      run: sudo /etc/init.d/mysql start

    - uses: actions/checkout@v2

    - name: Copy phpunit.xml.dist
      run: php -r "file_exists('phpunit.xml.dist') || copy('phpunit.xml.dist', 'phpunit.xml');"

    - name: Validate composer.json e composer.lock
      run: composer validate

    - name: Install dependencys
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Execute testes
      run: vendor/bin/phpunit