name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ homologation ]

jobs:
  php-unit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@abfbe6a46b637e038be212af3c5d3475b3e3213c
      with:
        php-version: '7.4'
        extensions: mbstring, dom, fileinfo, mysql

    - name: Start mysql
      run: sudo /etc/init.d/mysql start

    - name: Create database
      run: mysql -u root -proot -e "create database testing";

    - name: Copy phpunit.xml.dist
      run: php -r "file_exists('phpunit.xml.dist') || copy('phpunit.xml.dist', 'phpunit.xml');"

    - name: Validate composer.json e composer.lock
      run: composer validate

    - name: Install dependencys
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Execute testes
      run: vendor/bin/phpunit